// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type AudioMessagesDocumentDataSlicesSlice = AudioMessageSlice;

/**
 * Content for Audio Messages documents
 */
interface AudioMessagesDocumentData {
  /**
   * Slice Zone field in *Audio Messages*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: audio_messages.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<AudioMessagesDocumentDataSlicesSlice> /**
   * Meta Title field in *Audio Messages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: audio_messages.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Audio Messages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: audio_messages.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Audio Messages*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: audio_messages.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Audio Messages document from Prismic
 *
 * - **API ID**: `audio_messages`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AudioMessagesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AudioMessagesDocumentData>,
    "audio_messages",
    Lang
  >;

type EventsDocumentDataSlicesSlice = EventSlice;

/**
 * Content for events documents
 */
interface EventsDocumentData {
  /**
   * Slice Zone field in *events*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: events.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<EventsDocumentDataSlicesSlice> /**
   * Meta Title field in *events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: events.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: events.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *events*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: events.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * events document from Prismic
 *
 * - **API ID**: `events`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<EventsDocumentData>,
    "events",
    Lang
  >;

interface FootDocumentData {}

/**
 * foot document from Prismic
 *
 * - **API ID**: `foot`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FootDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<FootDocumentData>, "foot", Lang>;

type LifewaySessionsDocumentDataSlicesSlice = LifewaySessionsSlice;

/**
 * Content for lifeway sessions documents
 */
interface LifewaySessionsDocumentData {
  /**
   * Slice Zone field in *lifeway sessions*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: lifeway_sessions.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<LifewaySessionsDocumentDataSlicesSlice> /**
   * Meta Title field in *lifeway sessions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: lifeway_sessions.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *lifeway sessions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: lifeway_sessions.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *lifeway sessions*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: lifeway_sessions.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * lifeway sessions document from Prismic
 *
 * - **API ID**: `lifeway_sessions`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LifewaySessionsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LifewaySessionsDocumentData>,
    "lifeway_sessions",
    Lang
  >;

type MediaCenterDocumentDataSlicesSlice = MessageSlice;

/**
 * Content for media center documents
 */
interface MediaCenterDocumentData {
  /**
   * Slice Zone field in *media center*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: media_center.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<MediaCenterDocumentDataSlicesSlice> /**
   * Meta Title field in *media center*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: media_center.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *media center*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: media_center.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *media center*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media_center.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * media center document from Prismic
 *
 * - **API ID**: `media_center`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MediaCenterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MediaCenterDocumentData>,
    "media_center",
    Lang
  >;

export type AllDocumentTypes =
  | AudioMessagesDocument
  | EventsDocument
  | FootDocument
  | LifewaySessionsDocument
  | MediaCenterDocument;

/**
 * Primary content in *AudioMessage → Default → Primary*
 */
export interface AudioMessageSliceDefaultPrimary {
  /**
   * message title field in *AudioMessage → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: audio_message.default.primary.message_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  message_title: prismic.KeyTextField;

  /**
   * date field in *AudioMessage → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: audio_message.default.primary.date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  date: prismic.DateField;

  /**
   * message audio link field in *AudioMessage → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: audio_message.default.primary.message_audio_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  message_audio_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * minister field in *AudioMessage → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: audio_message.default.primary.minister
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  minister: prismic.KeyTextField;

  /**
   * thumbnail field in *AudioMessage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: audio_message.default.primary.thumbnail
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  thumbnail: prismic.ImageField<never>;
}

/**
 * Default variation for AudioMessage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AudioMessageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AudioMessageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AudioMessage*
 */
type AudioMessageSliceVariation = AudioMessageSliceDefault;

/**
 * AudioMessage Shared Slice
 *
 * - **API ID**: `audio_message`
 * - **Description**: AudioMessage
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AudioMessageSlice = prismic.SharedSlice<
  "audio_message",
  AudioMessageSliceVariation
>;

/**
 * Item in *Event → Default → Primary → tags*
 */
export interface EventSliceDefaultPrimaryTagsItem {
  /**
   * tag name field in *Event → Default → Primary → tags*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.default.primary.tags[].tag_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tag_name: prismic.KeyTextField;
}

/**
 * Primary content in *Event → Default → Primary*
 */
export interface EventSliceDefaultPrimary {
  /**
   * image field in *Event → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: event.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * event name field in *Event → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.default.primary.event_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  event_name: prismic.KeyTextField;

  /**
   * short description field in *Event → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.default.primary.short_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  short_description: prismic.KeyTextField;

  /**
   * tags field in *Event → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: event.default.primary.tags[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  tags: prismic.GroupField<Simplify<EventSliceDefaultPrimaryTagsItem>>;

  /**
   * start date and time field in *Event → Default → Primary*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: event.default.primary.start_date_and_time
   * - **Documentation**: https://prismic.io/docs/fields/timestamp
   */
  start_date_and_time: prismic.TimestampField;

  /**
   * end date and time field in *Event → Default → Primary*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: event.default.primary.end_date_and_time
   * - **Documentation**: https://prismic.io/docs/fields/timestamp
   */
  end_date_and_time: prismic.TimestampField;
}

/**
 * Default variation for Event Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EventSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EventSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Event*
 */
type EventSliceVariation = EventSliceDefault;

/**
 * Event Shared Slice
 *
 * - **API ID**: `event`
 * - **Description**: Event
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EventSlice = prismic.SharedSlice<"event", EventSliceVariation>;

/**
 * Primary content in *LifewaySessions → Default → Primary*
 */
export interface LifewaySessionsSliceDefaultPrimary {
  /**
   * date field in *LifewaySessions → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: lifeway_sessions.default.primary.date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  date: prismic.DateField;

  /**
   * message title field in *LifewaySessions → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lifeway_sessions.default.primary.message_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  message_title: prismic.KeyTextField;

  /**
   * embed link field in *LifewaySessions → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lifeway_sessions.default.primary.embed_link
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  embed_link: prismic.KeyTextField;

  /**
   * minister field in *LifewaySessions → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lifeway_sessions.default.primary.minister
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  minister: prismic.KeyTextField;

  /**
   * description field in *LifewaySessions → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lifeway_sessions.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * scriptures field in *LifewaySessions → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lifeway_sessions.default.primary.scriptures
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  scriptures: prismic.KeyTextField;
}

/**
 * Default variation for LifewaySessions Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LifewaySessionsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LifewaySessionsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LifewaySessions*
 */
type LifewaySessionsSliceVariation = LifewaySessionsSliceDefault;

/**
 * LifewaySessions Shared Slice
 *
 * - **API ID**: `lifeway_sessions`
 * - **Description**: LifewaySessions
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LifewaySessionsSlice = prismic.SharedSlice<
  "lifeway_sessions",
  LifewaySessionsSliceVariation
>;

/**
 * Primary content in *Message → Default → Primary*
 */
export interface MessageSliceDefaultPrimary {
  /**
   * date field in *Message → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: message.default.primary.date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  date: prismic.DateField;

  /**
   * message title field in *Message → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: message.default.primary.message_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  message_title: prismic.KeyTextField;

  /**
   * minister field in *Message → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: message.default.primary.minister
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  minister: prismic.KeyTextField;

  /**
   * embed link field in *Message → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: message.default.primary.embed_link
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  embed_link: prismic.RichTextField;

  /**
   * description field in *Message → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: message.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * scriptures field in *Message → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: message.default.primary.scriptures
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  scriptures: prismic.KeyTextField;
}

/**
 * Default variation for Message Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MessageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MessageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Message*
 */
type MessageSliceVariation = MessageSliceDefault;

/**
 * Message Shared Slice
 *
 * - **API ID**: `message`
 * - **Description**: Message
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MessageSlice = prismic.SharedSlice<
  "message",
  MessageSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AudioMessagesDocument,
      AudioMessagesDocumentData,
      AudioMessagesDocumentDataSlicesSlice,
      EventsDocument,
      EventsDocumentData,
      EventsDocumentDataSlicesSlice,
      FootDocument,
      FootDocumentData,
      LifewaySessionsDocument,
      LifewaySessionsDocumentData,
      LifewaySessionsDocumentDataSlicesSlice,
      MediaCenterDocument,
      MediaCenterDocumentData,
      MediaCenterDocumentDataSlicesSlice,
      AllDocumentTypes,
      AudioMessageSlice,
      AudioMessageSliceDefaultPrimary,
      AudioMessageSliceVariation,
      AudioMessageSliceDefault,
      EventSlice,
      EventSliceDefaultPrimaryTagsItem,
      EventSliceDefaultPrimary,
      EventSliceVariation,
      EventSliceDefault,
      LifewaySessionsSlice,
      LifewaySessionsSliceDefaultPrimary,
      LifewaySessionsSliceVariation,
      LifewaySessionsSliceDefault,
      MessageSlice,
      MessageSliceDefaultPrimary,
      MessageSliceVariation,
      MessageSliceDefault,
    };
  }
}
