// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  event: defineAsyncComponent(() => import("./Event/index.vue")),
  message: defineAsyncComponent(() => import("./Message/index.vue")),
});
