// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  audio_message: defineAsyncComponent(() => import("./AudioMessage/index.vue")),
  event: defineAsyncComponent(() => import("./Event/index.vue")),
  lifeway_sessions: defineAsyncComponent(
    () => import("./LifewaySessions/index.vue"),
  ),
  message: defineAsyncComponent(() => import("./Message/index.vue")),
});
